# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PumpkinPi2.0' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PumpkinPi2.0

  target 'PumpkinPi2.0Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PumpkinPi2.0UITests' do
    # Pods for testing
  end


pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Database'
pod 'Firebase/Functions'
pod 'Firebase/Storage'

end
